[tools]
go = "1.24"

[tasks.install-go-tools]
description = "Install Go tools for development"
run = """
#!/usr/bin/env bash
set -e

go install golang.org/x/tools/gopls@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install github.com/go-delve/delve/cmd/dlv@latest

echo "✅ Go tools installed"
"""
